# Site settings
title: "That Never Fading Smile"
email: gal@dng.io
description: > # this means to ignore newlines until "baseurl:"
  For Lev That Never Fading Smile, Want to hear more great music? Check back every Wednesday
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://thatneverfadingsmile.com" # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown
permalink: ":title/"
highlighter: pygments

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Minification
sass:
  style: compressed
